<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Tour;

class TourSeeder extends Seeder
{
    public function run(): void
    {
        $tours = [
            // ADVENTURE TOURS (Category 1) - 8 tours
            [
                'name' => 'Bali Adventure Complete Package',
                'description' => 'Experience the ultimate Bali adventure with volcano trekking, white water rafting, ATV rides, and traditional cultural visits. Perfect for thrill-seekers!',
                'price' => 13500000,
                'duration' => '5 Days 4 Nights',
                'destination' => 'Bali, Indonesia',
                'departure_location' => 'Jakarta',
                'category_id' => 1,
                'max_participants' => 30,
                'start_date' => now()->addDays(10),
                'end_date' => now()->addDays(15),
                'available_from' => now(),
                'available_until' => now()->addMonths(6),
                'highlights' => ['Mount Batur Sunrise Trek', 'White Water Rafting', 'ATV Ride', 'Tanah Lot Temple', 'Traditional Massage'],
                'included' => ['Round-trip flights', '4 nights hotel', 'Daily breakfast', 'Tour guide', 'All entrance tickets', 'Airport transfers'],
                'excluded' => ['Lunch & dinner', 'Personal expenses', 'Travel insurance', 'Optional activities'],
            ],
            [
                'name' => 'Bromo Ijen Crater Adventure',
                'description' => 'Witness the famous Blue Fire of Ijen Crater and stunning sunrise at Mount Bromo. An unforgettable volcanic adventure!',
                'price' => 8500000,
                'duration' => '4 Days 3 Nights',
                'destination' => 'East Java, Indonesia',
                'departure_location' => 'Surabaya',
                'category_id' => 1,
                'max_participants' => 25,
                'start_date' => now()->addDays(15),
                'end_date' => now()->addDays(19),
                'available_from' => now(),
                'available_until' => now()->addMonths(6),
                'highlights' => ['Ijen Blue Fire', 'Mount Bromo Sunrise', 'Madakaripura Waterfall', 'Jeep Adventure', 'Local Coffee Plantation'],
                'included' => ['Transportation', 'Hotel accommodation', 'Breakfast daily', 'Tour guide', 'Gas masks', 'Entrance fees'],
                'excluded' => ['Flights', 'Meals (lunch/dinner)', 'Personal expenses', 'Tips for guide'],
            ],
            [
                'name' => 'Raja Ampat Diving Expedition',
                'description' => 'Explore the world\'s richest marine biodiversity in Raja Ampat with multiple diving sites and island hopping adventures.',
                'price' => 18500000,
                'duration' => '6 Days 5 Nights',
                'destination' => 'Raja Ampat, Papua',
                'departure_location' => 'Jakarta',
                'category_id' => 1,
                'max_participants' => 15,
                'start_date' => now()->addDays(20),
                'end_date' => now()->addDays(26),
                'available_from' => now(),
                'available_until' => now()->addMonths(8),
                'highlights' => ['10+ Dive Sites', 'Pianemo Islands', 'Piaynemo Viewpoint', 'Manta Ray Spot', 'Marine Life Photography'],
                'included' => ['Flights', 'Liveaboard accommodation', 'All meals', 'Dive equipment', 'Dive master', 'Island hopping'],
                'excluded' => ['Diving certification', 'Underwater camera', 'Alcoholic beverages', 'Travel insurance'],
            ],
            [
                'name' => 'Komodo Dragon Safari',
                'description' => 'Meet the legendary Komodo dragons and explore the stunning pink beaches and crystal-clear waters of Komodo National Park.',
                'price' => 12000000,
                'duration' => '4 Days 3 Nights',
                'destination' => 'Komodo National Park, NTT',
                'departure_location' => 'Bali',
                'category_id' => 1,
                'max_participants' => 20,
                'start_date' => now()->addDays(25),
                'end_date' => now()->addDays(29),
                'available_from' => now(),
                'available_until' => now()->addMonths(6),
                'highlights' => ['Komodo Dragon Encounter', 'Pink Beach', 'Padar Island Trek', 'Snorkeling 3 spots', 'Sunset at Kalong Island'],
                'included' => ['Boat charter', 'Accommodation', 'All meals', 'Snorkeling gear', 'Park ranger', 'Entrance fees'],
                'excluded' => ['Flights to Labuan Bajo', 'Drone permit', 'Underwater camera', 'Tips'],
            ],
            [
                'name' => 'Trekking Mount Rinjani Summit',
                'description' => 'Conquer Indonesia\'s second-highest volcano! Trek to Rinjani summit and witness the breathtaking Segara Anak crater lake.',
                'price' => 7500000,
                'duration' => '4 Days 3 Nights',
                'destination' => 'Lombok, Indonesia',
                'departure_location' => 'Lombok',
                'category_id' => 1,
                'max_participants' => 12,
                'start_date' => now()->addDays(30),
                'end_date' => now()->addDays(34),
                'available_from' => now()->addMonths(1),
                'available_until' => now()->addMonths(5),
                'highlights' => ['Summit at 3,726m', 'Segara Anak Lake', 'Hot Springs', 'Camping under stars', 'Sunrise viewpoint'],
                'included' => ['Trekking permit', 'Porter & guide', 'Camping equipment', 'All meals during trek', 'Mountain insurance'],
                'excluded' => ['Hotel before/after trek', 'Personal trekking gear', 'Tips for porters', 'Extra food'],
            ],
            [
                'name' => 'Rafting Citarik Extreme',
                'description' => 'Adrenaline-pumping white water rafting experience on the challenging rapids of Citarik River in West Java.',
                'price' => 2500000,
                'duration' => '1 Day',
                'destination' => 'Sukabumi, West Java',
                'departure_location' => 'Jakarta/Bandung',
                'category_id' => 1,
                'max_participants' => 40,
                'start_date' => now()->addDays(5),
                'end_date' => now()->addDays(5),
                'available_from' => now(),
                'available_until' => now()->addMonths(12),
                'highlights' => ['Class III-IV Rapids', 'Expert River Guides', 'Safety Equipment', 'Lunch Buffet', 'Photo Documentation'],
                'included' => ['Transportation from Jakarta', 'Rafting equipment', 'Safety briefing', 'Lunch', 'Insurance', 'Photos'],
                'excluded' => ['Personal expenses', 'Extra meals', 'Accommodation'],
            ],
            [
                'name' => 'Canyoning Green Canyon',
                'description' => 'Navigate through stunning Green Canyon with body rafting, cliff jumping, and cave exploration in pristine natural surroundings.',
                'price' => 3200000,
                'duration' => '2 Days 1 Night',
                'destination' => 'Pangandaran, West Java',
                'departure_location' => 'Bandung',
                'category_id' => 1,
                'max_participants' => 25,
                'start_date' => now()->addDays(12),
                'end_date' => now()->addDays(14),
                'available_from' => now(),
                'available_until' => now()->addMonths(10),
                'highlights' => ['Body Rafting', 'Cliff Jumping', 'Cave Exploration', 'Boat Ride', 'Waterfall Swimming'],
                'included' => ['Transportation', 'Hotel', 'Breakfast', 'Canyoning equipment', 'Guide', 'Boat tickets'],
                'excluded' => ['Lunch & dinner', 'Personal gear', 'Tips'],
            ],
            [
                'name' => 'Paragliding Batu Malang',
                'description' => 'Soar above the beautiful valleys of Batu with tandem paragliding. Experience the thrill of flying with stunning mountain views!',
                'price' => 1500000,
                'duration' => '1 Day',
                'destination' => 'Batu, Malang',
                'departure_location' => 'Malang/Surabaya',
                'category_id' => 1,
                'max_participants' => 20,
                'start_date' => now()->addDays(8),
                'end_date' => now()->addDays(8),
                'available_from' => now(),
                'available_until' => now()->addMonths(12),
                'highlights' => ['Tandem Paragliding', 'Professional Pilot', 'Aerial Photography', 'Mountain Views', 'Safety Certified'],
                'included' => ['Paragliding flight', 'Safety equipment', 'Insurance', 'Photo & video', 'Certificate'],
                'excluded' => ['Transportation', 'Meals', 'Accommodation'],
            ],

            // BEACH TOURS (Category 2) - 7 tours
            [
                'name' => 'Maldives Beach Paradise Premium',
                'description' => 'Escape to tropical paradise with overwater villa, crystal-clear waters, world-class diving, and romantic sunset cruises.',
                'price' => 28000000,
                'duration' => '6 Days 5 Nights',
                'destination' => 'Maldives',
                'departure_location' => 'Jakarta',
                'category_id' => 2,
                'max_participants' => 20,
                'start_date' => now()->addDays(15),
                'end_date' => now()->addDays(21),
                'available_from' => now(),
                'available_until' => now()->addYear(),
                'highlights' => ['Overwater Bungalow', 'Private Beach', 'Scuba Diving', 'Sunset Cruise', 'Spa & Wellness'],
                'included' => ['Flights', '5 nights luxury resort', 'All meals', 'Water sports', 'Speedboat transfers', 'Spa session'],
                'excluded' => ['Alcoholic drinks', 'Diving certification', 'Personal expenses', 'Travel insurance'],
            ],
            [
                'name' => 'Gili Islands Tropical Escape',
                'description' => 'Explore the three Gili islands with snorkeling, cycling, and beachfront relaxation. No cars, no stress, pure paradise!',
                'price' => 6500000,
                'duration' => '4 Days 3 Nights',
                'destination' => 'Gili Islands, Lombok',
                'departure_location' => 'Lombok',
                'category_id' => 2,
                'max_participants' => 30,
                'start_date' => now()->addDays(10),
                'end_date' => now()->addDays(14),
                'available_from' => now(),
                'available_until' => now()->addMonths(8),
                'highlights' => ['Island Hopping', 'Turtle Snorkeling', 'Bicycle Tour', 'Sunset Beach', 'Beach BBQ'],
                'included' => ['Hotel beachfront', 'Breakfast daily', 'Snorkeling gear', 'Island hopping tour', 'Bicycle rental'],
                'excluded' => ['Flights', 'Lunch & dinner', 'Diving', 'Spa treatments'],
            ],
            [
                'name' => 'Nusa Penida Island Adventure',
                'description' => 'Discover the hidden gems of Nusa Penida: Kelingking Beach, Angel Billabong, and incredible manta ray diving spots.',
                'price' => 5500000,
                'duration' => '3 Days 2 Nights',
                'destination' => 'Nusa Penida, Bali',
                'departure_location' => 'Bali',
                'category_id' => 2,
                'max_participants' => 25,
                'start_date' => now()->addDays(18),
                'end_date' => now()->addDays(21),
                'available_from' => now(),
                'available_until' => now()->addMonths(10),
                'highlights' => ['Kelingking T-Rex Beach', 'Angel Billabong', 'Broken Beach', 'Manta Point Snorkeling', 'Crystal Bay'],
                'included' => ['Fast boat tickets', 'Hotel', 'Breakfast', 'Island tour', 'Snorkeling gear', 'Local guide'],
                'excluded' => ['Meals (lunch/dinner)', 'Drone permit', 'Diving', 'Tips'],
            ],
            [
                'name' => 'Belitung Island Beach Hopping',
                'description' => 'Explore pristine beaches with unique granite rock formations and enjoy island hopping around Belitung archipelago.',
                'price' => 7800000,
                'duration' => '4 Days 3 Nights',
                'destination' => 'Belitung Island',
                'departure_location' => 'Jakarta',
                'category_id' => 2,
                'max_participants' => 20,
                'start_date' => now()->addDays(22),
                'end_date' => now()->addDays(26),
                'available_from' => now(),
                'available_until' => now()->addMonths(6),
                'highlights' => ['Tanjung Tinggi Beach', 'Lengkuas Lighthouse', 'Island Hopping 5 islands', 'Snorkeling', 'Fresh Seafood'],
                'included' => ['Flights', 'Hotel', 'Breakfast', 'Island hopping boat', 'Snorkeling gear', 'Lunch during tour'],
                'excluded' => ['Dinner', 'Alcoholic beverages', 'Personal expenses', 'Lighthouse entrance'],
            ],
            [
                'name' => 'Derawan Islands Diving Package',
                'description' => 'Dive with jellyfish, turtles, and manta rays in the pristine waters of Derawan, Kakaban, and Maratua islands.',
                'price' => 14500000,
                'duration' => '5 Days 4 Nights',
                'destination' => 'Derawan Islands, Kalimantan',
                'departure_location' => 'Balikpapan',
                'category_id' => 2,
                'max_participants' => 15,
                'start_date' => now()->addDays(28),
                'end_date' => now()->addDays(33),
                'available_from' => now(),
                'available_until' => now()->addMonths(8),
                'highlights' => ['Stingless Jellyfish Lake', 'Turtle Conservation', '10+ Dive Sites', 'Manta Ray Spot', 'Island Hopping'],
                'included' => ['Flights', 'Homestay', 'All meals', 'Boat charter', 'Dive master', 'Snorkeling gear'],
                'excluded' => ['Diving equipment rental', 'Alcoholic drinks', 'Tips', 'Travel insurance'],
            ],
            [
                'name' => 'Phuket Beach & Party',
                'description' => 'Experience Thailand\'s most famous beach destination with island tours, beach clubs, and vibrant nightlife in Patong.',
                'price' => 9500000,
                'duration' => '5 Days 4 Nights',
                'destination' => 'Phuket, Thailand',
                'departure_location' => 'Jakarta',
                'category_id' => 2,
                'max_participants' => 35,
                'start_date' => now()->addDays(25),
                'end_date' => now()->addDays(30),
                'available_from' => now(),
                'available_until' => now()->addMonths(12),
                'highlights' => ['Phi Phi Islands', 'James Bond Island', 'Beach Clubs', 'Thai Massage', 'Patong Nightlife'],
                'included' => ['Flights', '4* Hotel', 'Breakfast', 'Airport transfers', 'Phi Phi tour', 'SIM card'],
                'excluded' => ['Visa fees', 'Lunch & dinner', 'Nightclub entries', 'Personal expenses'],
            ],
            [
                'name' => 'Krabi Island Explorer',
                'description' => 'Discover the beauty of Krabi with Railay Beach rock climbing, island hopping, and emerald pool jungle trekking.',
                'price' => 8800000,
                'duration' => '4 Days 3 Nights',
                'destination' => 'Krabi, Thailand',
                'departure_location' => 'Bangkok',
                'category_id' => 2,
                'max_participants' => 25,
                'start_date' => now()->addDays(32),
                'end_date' => now()->addDays(36),
                'available_from' => now(),
                'available_until' => now()->addMonths(10),
                'highlights' => ['Railay Beach', 'Rock Climbing', '4 Islands Tour', 'Emerald Pool', 'Hot Springs'],
                'included' => ['Hotel', 'Breakfast', 'Long-tail boat tours', 'Climbing gear', 'Local guide', 'Entrance fees'],
                'excluded' => ['Flights', 'Meals (lunch/dinner)', 'Tips', 'Personal gear'],
            ],

            // CULTURAL TOURS (Category 3) - 6 tours
            [
                'name' => 'Yogyakarta Cultural Heritage',
                'description' => 'Immerse yourself in Javanese culture with visits to Borobudur, Prambanan, Sultan Palace, and traditional batik workshops.',
                'price' => 5500000,
                'duration' => '4 Days 3 Nights',
                'destination' => 'Yogyakarta, Indonesia',
                'departure_location' => 'Jakarta',
                'category_id' => 3,
                'max_participants' => 30,
                'start_date' => now()->addDays(12),
                'end_date' => now()->addDays(16),
                'available_from' => now(),
                'available_until' => now()->addMonths(12),
                'highlights' => ['Borobudur Sunrise', 'Prambanan Temple', 'Kraton Palace', 'Batik Workshop', 'Wayang Kulit Show'],
                'included' => ['Flights', 'Hotel', 'Breakfast', 'Temple entrance fees', 'Private guide', 'Batik class'],
                'excluded' => ['Lunch & dinner', 'Personal shopping', 'Optional activities', 'Tips'],
            ],
            [
                'name' => 'Tokyo Cultural Immersion',
                'description' => 'Experience authentic Japanese culture with tea ceremonies, temple visits, samurai training, and traditional kaiseki dining.',
                'price' => 22000000,
                'duration' => '6 Days 5 Nights',
                'destination' => 'Tokyo, Japan',
                'departure_location' => 'Jakarta',
                'category_id' => 3,
                'max_participants' => 20,
                'start_date' => now()->addDays(30),
                'end_date' => now()->addDays(36),
                'available_from' => now(),
                'available_until' => now()->addMonths(10),
                'highlights' => ['Tea Ceremony', 'Senso-ji Temple', 'Samurai Experience', 'Mt. Fuji Day Trip', 'Traditional Ryokan'],
                'included' => ['Flights', 'Hotel', 'Daily breakfast', 'JR Pass 5 days', 'Cultural activities', 'English guide'],
                'excluded' => ['Visa', 'Lunch & dinner', 'Personal expenses', 'Travel insurance'],
            ],
            [
                'name' => 'Ubud Spiritual & Wellness Retreat',
                'description' => 'Find inner peace in Ubud with yoga sessions, meditation, traditional healing, and visits to ancient temples and rice terraces.',
                'price' => 9500000,
                'duration' => '5 Days 4 Nights',
                'destination' => 'Ubud, Bali',
                'departure_location' => 'Jakarta',
                'category_id' => 3,
                'max_participants' => 15,
                'start_date' => now()->addDays(15),
                'end_date' => now()->addDays(20),
                'available_from' => now(),
                'available_until' => now()->addMonths(8),
                'highlights' => ['Daily Yoga', 'Balinese Massage', 'Healer Consultation', 'Rice Terrace Trek', 'Sacred Monkey Forest'],
                'included' => ['Boutique hotel', 'Vegetarian meals', 'Yoga classes', 'Spa treatments', 'Temple tours', 'Airport transfers'],
                'excluded' => ['Flights', 'Additional spa', 'Shopping', 'Tips'],
            ],
            [
                'name' => 'Toraja Funeral Ceremony Experience',
                'description' => 'Witness the unique Rambu Solo funeral ceremony and explore the ancient burial caves and traditional Tongkonan houses.',
                'price' => 11000000,
                'duration' => '5 Days 4 Nights',
                'destination' => 'Toraja, Sulawesi',
                'departure_location' => 'Makassar',
                'category_id' => 3,
                'max_participants' => 12,
                'start_date' => now()->addDays(40),
                'end_date' => now()->addDays(45),
                'available_from' => now()->addMonths(2),
                'available_until' => now()->addMonths(6),
                'highlights' => ['Rambu Solo Ceremony', 'Burial Caves', 'Tongkonan Houses', 'Traditional Village', 'Local Coffee Plantation'],
                'included' => ['Flights Makassar-Toraja', 'Hotel', 'Breakfast', 'Private car', 'Local guide', 'Entrance fees'],
                'excluded' => ['Flights to Makassar', 'Lunch & dinner', 'Ceremony offerings', 'Tips'],
            ],
            [
                'name' => 'Kyoto Ancient Capital Tour',
                'description' => 'Step back in time in Kyoto with visits to golden temples, bamboo forests, geisha districts, and traditional crafts.',
                'price' => 24000000,
                'duration' => '5 Days 4 Nights',
                'destination' => 'Kyoto, Japan',
                'departure_location' => 'Jakarta',
                'category_id' => 3,
                'max_participants' => 18,
                'start_date' => now()->addDays(35),
                'end_date' => now()->addDays(40),
                'available_from' => now(),
                'available_until' => now()->addMonths(12),
                'highlights' => ['Kinkaku-ji Golden Temple', 'Fushimi Inari Shrine', 'Arashiyama Bamboo', 'Gion Geisha District', 'Kaiseki Dinner'],
                'included' => ['Flights', '4* Hotel', 'Breakfast', 'Shinkansen tickets', 'Cultural tours', 'English guide'],
                'excluded' => ['Visa', 'Lunch & dinner', 'Shopping', 'Tips'],
            ],
            [
                'name' => 'Angkor Wat Temple Discovery',
                'description' => 'Explore the magnificent temples of Angkor including sunrise at Angkor Wat, Bayon, and the jungle-covered Ta Prohm.',
                'price' => 7800000,
                'duration' => '4 Days 3 Nights',
                'destination' => 'Siem Reap, Cambodia',
                'departure_location' => 'Jakarta',
                'category_id' => 3,
                'max_participants' => 25,
                'start_date' => now()->addDays(20),
                'end_date' => now()->addDays(24),
                'available_from' => now(),
                'available_until' => now()->addMonths(12),
                'highlights' => ['Angkor Wat Sunrise', 'Bayon Temple', 'Ta Prohm Jungle Temple', 'Tonle Sap Lake', 'Apsara Dance Show'],
                'included' => ['Flights', 'Hotel', 'Breakfast', 'Temple pass', 'Tuk-tuk transport', 'English guide'],
                'excluded' => ['Visa on arrival $30', 'Lunch & dinner', 'Tips', 'Balloon ride'],
            ],

            // MOUNTAIN TOURS (Category 4) - 5 tours
            [
                'name' => 'Mount Everest Base Camp Trek Premium',
                'description' => 'Trek to the base of the world\'s highest mountain with experienced Sherpa guides, comfortable lodges, and helicopter return option.',
                'price' => 45000000,
                'duration' => '14 Days 13 Nights',
                'destination' => 'Everest Region, Nepal',
                'departure_location' => 'Kathmandu',
                'category_id' => 4,
                'max_participants' => 12,
                'start_date' => now()->addDays(60),
                'end_date' => now()->addDays(74),
                'available_from' => now()->addMonths(2),
                'available_until' => now()->addMonths(8),
                'highlights' => ['Everest Base Camp 5,364m', 'Kala Patthar Viewpoint', 'Sherpa Village', 'Buddhist Monasteries', 'Helicopter Return Option'],
                'included' => ['Flights Jakarta-Kathmandu', 'Kathmandu hotel 2N', 'Domestic flights', 'All permits', 'Sherpa guide', 'Accommodation during trek', 'All meals during trek'],
                'excluded' => ['Nepal visa $50', 'Travel insurance mandatory', 'Personal trekking gear', 'Tips for guides', 'Helicopter return +$1200'],
            ],
            [
                'name' => 'Kilimanjaro Summit Expedition',
                'description' => 'Conquer Africa\'s highest peak via the scenic Machame Route with professional guides and porters supporting your journey.',
                'price' => 52000000,
                'duration' => '10 Days 9 Nights',
                'destination' => 'Mount Kilimanjaro, Tanzania',
                'departure_location' => 'Jakarta',
                'category_id' => 4,
                'max_participants' => 10,
                'start_date' => now()->addDays(90),
                'end_date' => now()->addDays(100),
                'available_from' => now()->addMonths(3),
                'available_until' => now()->addMonths(9),
                'highlights' => ['Uhuru Peak 5,895m', 'Machame Route', 'Professional Mountain Guide', 'Porter Support', 'Summit Certificate'],
                'included' => ['Flights', 'Hotel Moshi 2N', 'Park fees', 'Mountain guide & porters', 'Camping equipment', 'All meals on mountain'],
                'excluded' => ['Visa $50', 'Tipping guides $250-300', 'Personal gear', 'Travel insurance', 'Extra hotel nights'],
            ],
            [
                'name' => 'Mount Bromo Sunrise Short Trek',
                'description' => 'Experience the iconic sunrise at Mount Bromo with jeep ride to viewpoint and walk across the Sea of Sand to the crater.',
                'price' => 2800000,
                'duration' => '2 Days 1 Night',
                'destination' => 'Mount Bromo, East Java',
                'departure_location' => 'Surabaya',
                'category_id' => 4,
                'max_participants' => 35,
                'start_date' => now()->addDays(8),
                'end_date' => now()->addDays(10),
                'available_from' => now(),
                'available_until' => now()->addMonths(12),
                'highlights' => ['Bromo Sunrise', 'Jeep 4x4', 'Sea of Sand', 'Crater Walk', 'Madakaripura Waterfall'],
                'included' => ['Transportation Surabaya PP', 'Hotel near Bromo', 'Breakfast', 'Jeep rental', 'Entrance fees', 'Local guide'],
                'excluded' => ['Meals (lunch/dinner)', 'Horse rental optional', 'Tips', 'Personal expenses'],
            ],
            [
                'name' => 'Mount Semeru Summit Challenge',
                'description' => 'Summit Java\'s highest peak, the active volcano Semeru at 3,676m, and camp at beautiful Ranu Kumbolo lake.',
                'price' => 6500000,
                'duration' => '5 Days 4 Nights',
                'destination' => 'Mount Semeru, East Java',
                'departure_location' => 'Malang',
                'category_id' => 4,
                'max_participants' => 15,
                'start_date' => now()->addDays(45),
                'end_date' => now()->addDays(50),
                'available_from' => now()->addMonths(1),
                'available_until' => now()->addMonths(6),
                'highlights' => ['Summit 3,676m', 'Ranu Kumbolo Lake', 'Oro-oro Ombo Savanna', 'Active Crater', 'Camping under stars'],
                'included' => ['Trekking permit', 'Porter service', 'Camping equipment', 'All meals during trek', 'Mountain guide', 'Insurance'],
                'excluded' => ['Transportation to Malang', 'Hotel before/after', 'Personal gear', 'Extra porter for personal bag', 'Tips'],
            ],
            [
                'name' => 'Swiss Alps Panoramic Tour',
                'description' => 'Experience the breathtaking Swiss Alps with train rides through mountain passes, cable car adventures, and charming alpine villages.',
                'price' => 58000000,
                'duration' => '8 Days 7 Nights',
                'destination' => 'Swiss Alps, Switzerland',
                'departure_location' => 'Jakarta',
                'category_id' => 4,
                'max_participants' => 20,
                'start_date' => now()->addDays(75),
                'end_date' => now()->addDays(83),
                'available_from' => now()->addMonths(2),
                'available_until' => now()->addMonths(10),
                'highlights' => ['Jungfraujoch Top of Europe', 'Matterhorn Glacier Paradise', 'Gornergrat Railway', 'Lake Geneva Cruise', 'Chocolate Factory'],
                'included' => ['Flights', '4* Hotels', 'Breakfast daily', 'Swiss Travel Pass', 'Cable cars & trains', 'English guide'],
                'excluded' => ['Schengen visa', 'Lunch & dinner', 'Personal expenses', 'Travel insurance', 'Tips'],
            ],

            // CITY TOURS (Category 5) - 6 tours
            [
                'name' => 'Singapore City Explorer',
                'description' => 'Discover the Lion City with visits to Marina Bay, Gardens by the Bay, Universal Studios, and vibrant hawker centers.',
                'price' => 8500000,
                'duration' => '4 Days 3 Nights',
                'destination' => 'Singapore',
                'departure_location' => 'Jakarta',
                'category_id' => 5,
                'max_participants' => 30,
                'start_date' => now()->addDays(10),
                'end_date' => now()->addDays(14),
                'available_from' => now(),
                'available_until' => now()->addYear(),
                'highlights' => ['Marina Bay Sands', 'Gardens by the Bay', 'Universal Studios', 'Sentosa Island', 'Clarke Quay'],
                'included' => ['Flights', '3* Hotel', 'Breakfast', 'Universal Studios ticket', 'City tour', 'MRT tourist pass'],
                'excluded' => ['Visa (free for Indonesians)', 'Lunch & dinner', 'Shopping', 'Additional attractions'],
            ],
            [
                'name' => 'Paris City of Romance',
                'description' => 'Fall in love with Paris! Visit the Eiffel Tower, Louvre Museum, cruise the Seine, and indulge in French cuisine.',
                'price' => 32000000,
                'duration' => '6 Days 5 Nights',
                'destination' => 'Paris, France',
                'departure_location' => 'Jakarta',
                'category_id' => 5,
                'max_participants' => 25,
                'start_date' => now()->addDays(50),
                'end_date' => now()->addDays(56),
                'available_from' => now(),
                'available_until' => now()->addMonths(12),
                'highlights' => ['Eiffel Tower', 'Louvre Museum', 'Versailles Palace', 'Seine River Cruise', 'Montmartre District'],
                'included' => ['Flights', '3* Hotel central', 'Breakfast', 'Museum passes', 'Seine cruise', 'Metro pass'],
                'excluded' => ['Schengen visa €80', 'Lunch & dinner', 'Shopping', 'Tips', 'Travel insurance'],
            ],
            [
                'name' => 'Dubai Modern Marvel',
                'description' => 'Experience luxury in Dubai with Burj Khalifa, desert safari, gold souk, and yacht cruise along the Palm Jumeirah.',
                'price' => 18500000,
                'duration' => '5 Days 4 Nights',
                'destination' => 'Dubai, UAE',
                'departure_location' => 'Jakarta',
                'category_id' => 5,
                'max_participants' => 30,
                'start_date' => now()->addDays(25),
                'end_date' => now()->addDays(30),
                'available_from' => now(),
                'available_until' => now()->addYear(),
                'highlights' => ['Burj Khalifa 124th Floor', 'Desert Safari with BBQ', 'Dubai Mall', 'Gold Souk', 'Dhow Cruise'],
                'included' => ['Flights', '4* Hotel', 'Breakfast', 'Dubai visa', 'All tours', 'Private transfers'],
                'excluded' => ['Lunch & dinner', 'Shopping', 'Burj Al Arab', 'Ski Dubai', 'Tips'],
            ],
            [
                'name' => 'Bangkok City & Temples',
                'description' => 'Explore Thailand\'s bustling capital with grand palaces, floating markets, rooftop bars, and authentic street food.',
                'price' => 6500000,
                'duration' => '4 Days 3 Nights',
                'destination' => 'Bangkok, Thailand',
                'departure_location' => 'Jakarta',
                'category_id' => 5,
                'max_participants' => 35,
                'start_date' => now()->addDays(15),
                'end_date' => now()->addDays(19),
                'available_from' => now(),
                'available_until' => now()->addYear(),
                'highlights' => ['Grand Palace', 'Wat Arun', 'Floating Market', 'Thai Massage', 'Rooftop Bar'],
                'included' => ['Flights', '3* Hotel', 'Breakfast', 'City temple tour', 'Floating market tour', 'Airport transfers'],
                'excluded' => ['Visa on arrival $35', 'Lunch & dinner', 'Nightlife', 'Shopping', 'Massage'],
            ],
            [
                'name' => 'New York City Experience',
                'description' => 'Experience the Big Apple with Statue of Liberty, Times Square, Central Park, Broadway show, and top observation decks.',
                'price' => 48000000,
                'duration' => '7 Days 6 Nights',
                'destination' => 'New York, USA',
                'departure_location' => 'Jakarta',
                'category_id' => 5,
                'max_participants' => 20,
                'start_date' => now()->addDays(60),
                'end_date' => now()->addDays(67),
                'available_from' => now()->addMonths(2),
                'available_until' => now()->addMonths(10),
                'highlights' => ['Statue of Liberty', 'Empire State Building', 'Central Park', 'Broadway Show', 'Brooklyn Bridge'],
                'included' => ['Flights', '3* Hotel Manhattan', 'Breakfast', 'City pass', 'Broadway ticket', 'Airport transfers'],
                'excluded' => ['US visa $185', 'Lunch & dinner', 'Shopping', 'Additional shows', 'Tips'],
            ],
            [
                'name' => 'Hong Kong City Adventure',
                'description' => 'Discover Hong Kong\'s blend of East and West with Victoria Peak, Disneyland, dim sum trails, and Temple Street market.',
                'price' => 12000000,
                'duration' => '5 Days 4 Nights',
                'destination' => 'Hong Kong',
                'departure_location' => 'Jakarta',
                'category_id' => 5,
                'max_participants' => 28,
                'start_date' => now()->addDays(20),
                'end_date' => now()->addDays(25),
                'available_from' => now(),
                'available_until' => now()->addYear(),
                'highlights' => ['Victoria Peak Tram', 'Hong Kong Disneyland', 'Symphony of Lights', 'Dim Sum Tour', 'Lantau Buddha'],
                'included' => ['Flights', '3* Hotel Kowloon', 'Breakfast', 'Disneyland ticket', 'Octopus card', 'City tours'],
                'excluded' => ['Visa (free for Indonesians)', 'Lunch & dinner', 'Shopping', 'Ocean Park', 'Cable car'],
            ],
        ];

        foreach ($tours as $tour) {
            Tour::create($tour);
        }
    }
}
